version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3030:3030
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=taskList
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_ROOT_PASSWORD=""

    